### ISSUE TITLE
415_UNSUPPORTED_MEDIA_TYPE error on action GET /inventory/0 

### ISSUE THREAD

**Issue by rishit13** [CSCI-GA-2820-FA22-003/inventory#39]
**Describe the bug**
When the inventory manager tries to read a record with id 0 (which technically does not exist), the code throws an error 415_UNSUPPORTED_MEDIA_TYPE, instead it should throw an error 404_NOT_FOUND

**To Reproduce**
1. Start flask application on visual studio code 
2. Open postman on web browser
3. Click on GET method type
4. Go to the URL text box and enter the following URL : "/inventory/0"
5. You should get an error unsupported "415_UNSUPPORTED_MEDIA_TYPE"

**Expected behavior**
When the inventory manager tries to read a record id  which does not exist, it should return 404_NOT_FOUND.

**Comment by sakshambassi** [comment]
This was completed in #78 right? pls link and close it if so
