### ISSUE TITLE
Checkout Feature

### ISSUE THREAD

**Issue by SAR2652** [CSCI-GA-2820-FA22-003/inventory#74]
**As an** Inventory Manager 
 **I need** a feature to update the quantity of the product
 **So that** I can track the remaining quantity of the product and its active state after placing an order 
   
 ### Details and Assumptions
 * A functioning update method for the Inventory Model
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a working Flask application
 When a call is made to the checkout feature
 Then the quantity of that feature is updated to the difference between the quantity within the database and the amount requested by the inventory manager
 ```

**Comment by sakshambassi** [comment]
was this completed in #72 ?

**Comment by SAR2652** [comment]
Yes

**Comment by sakshambassi** [comment]
you can attach the PR to this issue and close this out!
